# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: wget https://public.sn.files.1drv.com/y4mhest3q1iocPDCb7pbf7UuMHKMX_6dyyQ7nbbVKD6BBJuis68k_2kqigJ7CB2M0xsZqnr-H9tK1F9JxtCjlsLx9VDP28hVuCPFpA0oujYajf920llhrRtORSwae89jDnqtj7TsESu_Mcf_YEpQvsSR1FyOYx_sqnZCr5hJ2zEruVUUsW08xROOdqsTHrYJV2o72f9jGlGpC5shZOsZy6pwS1C9RxSYAwS659SqXeLl38 -O interprolog.jar
    - run: mvn install:install-file -Dfile=interprolog.jar -DgroupId=com.declarativa.interprolog -DartifactId=interprolog -Dversion=2.2a4 -Dpackaging=jar
    
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
